version: '3.7'
volumes:
    wordpress_data:
        driver: local
        driver_opts:
            type: none
            device: /home/sben-ela/data/wordpress
            o: bind
    mariadb_data:
        driver: local
        driver_opts:
            type: none
            device: /home/sben-ela/data/mariadb
            o: bind


services:
    nginx:
        build: ./nginx
        container_name: nginx
        image: nginx
        ports:
            - "443:443"
        depends_on:
            - wordpress
        volumes:
            - wordpress_data:/var/www/wordpress
        restart: always
        env_file:
            - .env

    wordpress:
        build: ./wordpress
        container_name: wordpress
        image: wordpress
        volumes:
            - wordpress_data:/var/www/wordpress
        restart: always
        env_file:
            - .env

    database:
        container_name: database
        build: ./mariadb
        image: mariadb
        restart: always
        volumes:
            - mariadb_data:/var/lib/mysql 
        env_file:
            - .env